import{a as f,S as y,i as a}from"./assets/vendor-CrAdtshy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const L="49001064-c7b72e374a4ae6399075933f6",w="https://pixabay.com/api/";let i=1;function E(){i=1}async function p(r){const t={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:i};try{const o=await f.get(w,{params:t});return i+=1,o.data}catch(o){throw console.error("Error fetching images:",o),o}}const u=document.querySelector(".loader");function g(){u.classList.remove("hidden")}function m(){u.classList.add("hidden")}function v(){document.getElementById("gallery").innerHTML=""}function h(r){const t=document.getElementById("gallery");r.forEach(s=>{const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`
      <a href="${s.largeImageURL}" class="gallery-link">
          <img src="${s.webformatURL}" alt="${s.tags}" class="gallery-image" />
      </a>
      <div class="info">
          <p>Likes <span>${s.likes}</span></p>
          <p>Views <span>${s.views}</span></p>
          <p>Comments <span>${s.comments}</span></p>
          <p>Downloads <span>${s.downloads}</span></p>
      </div>
  `,t.appendChild(e)}),new y(".gallery-link",{captionsData:"alt"}).refresh()}function b(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}const I=document.getElementById("search-form"),P=document.getElementById("search-input");document.querySelector(".loader");const c=document.getElementById("load-more");let l="";I.addEventListener("submit",async r=>{if(r.preventDefault(),l=P.value.trim(),l===""){a.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}v(),c.classList.add("hidden"),g(),E();try{const t=await p(l),o=t.hits;if(o.length===0)a.error({title:"Error",message:"No images found. Try another search!",position:"topRight"});else{h(o);const s=Math.ceil(t.totalHits/40);i<=s&&c.classList.remove("hidden")}}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{m()}});c.addEventListener("click",async()=>{g();try{const r=await p(l),t=r.hits,o=Math.ceil(r.totalHits/40);t.length===0||i>o?(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c.classList.add("hidden")):(h(t),b())}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
